gui:
  showIcons: false
os:
  edit: '[ -n "$NVIM" ] && nvr -l --remote {{filename}} || nvim {{filename}}'
  editAtLine: '[ -n "$NVIM" ] && nvr -l --remote +{{line}} {{filename}} || nvim +{{line}} {{filename}}'
  editAtLineAndWait: '[ -n "$NVIM" ] && nvr -l --remote-tab-wait +{{line}} {{filename}} || nvim +{{line}} {{filename}}'
  editInTerminal: true

git:
  paging:
    colorArg: always
    # pager: delta --paging=never --diff-so-fancy --max-line-length=0
    pager: diffr

confirmOnQuit: true
showCommandLog: true
customCommands:
  - key: 'P'
    command: '{{.Form.pushType}}'
    context: 'commits'
    prompts:
      - type: 'menu'
        title: 'What kind of push is it?'
        key: 'pushType'
        options:
          - value: 'git push'
            name: 'HEAD'
            description: 'push head to remote'
          - value: 'git push origin {{.SelectedCommit.Hash}}:{{.SelectedLocalBranch.Name }}'
            name: 'commit'
            description: 'push commit {{.SelectedCommit.Hash}} and below to remote'
