gui:
  showIcons: false
os:
  edit: '[ -n "$NVIM" ] && nvr -l --remote {{filename}} || nvim {{filename}}'
  editAtLine: '[ -n "$NVIM" ] && nvr -l --remote +{{line}} {{filename}} || nvim +{{line}} {{filename}}'
  editAtLineAndWait: '[ -n "$NVIM" ] && nvr -l --remote-tab-wait +{{line}} {{filename}} || nvim +{{line}} {{filename}}'
  editInTerminal: true

git:
  paging:
    colorArg: always
    pager: delta --paging=never --diff-so-fancy --max-line-length=0

confirmOnQuit: true
showCommandLog: true
