gui:
  showIcons: false
os:
  edit: 'nvim --server "$NVIM" --remote-tab {{filename}}'
  editAtLine: 'nvim --server "$NVIM" --remote-tab {{filename}}; [ -z "$NVIM" ] || nvim --server "$NVIM" --remote-send ":{{line}}<CR>"'
  editAtLineAndWait: 'nvim +{{line}} {{filename}}'
promptToReturnFromSubprocess: false
git:
  pagers:
    - colorArg: never
    # - colorArg: always
      # pager: delta --paging=never --diff-so-fancy --max-line-length=0
      # pager: ydiff -p cat -s --wrap --width={{columnWidth}}
      # pager: diffr
      pager: riff --no-pager
confirmOnQuit: true
showCommandLog: true
keybinding:
  universal:
    return:
      - '<esc>'
      - '<ctrl+[>'
customCommands:
  - key: 'P'
    command: '{{.Form.pushType}}'
    context: 'commits'
    prompts:
      - type: 'menu'
        title: 'What kind of push is it?'
        key: 'pushType'
        options:
          - value: 'git push origin {{.SelectedCommit.Hash}}:{{.CheckedOutBranch.Name }}'
            name: 'commit'
            description: 'push commit {{.SelectedCommit.Hash}} and below to remote'
          - value: 'git push'
            name: 'HEAD'
            description: 'push head to remote'
