#!/bin/sh
set -eu

config_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

case "$(uname -s)" in
  Darwin)
    platform_config=macos.conf
    platform_theme=
    ;;
  Linux)
    platform_config=linux.conf
    platform_theme='theme = noctalia'
    ;;
  *)
    echo "Unsupported platform: $(uname -s)" >&2
    exit 1
    ;;
esac

{
  echo '# Generated by select-platform.sh; do not commit.'
  echo 'config-file = common.conf'
  echo "config-file = $platform_config"
  if [ -n "$platform_theme" ]; then
    echo "$platform_theme"
  fi
} >"$config_dir/config.ghostty"

echo "Ghostty config: common.conf + $platform_config"
